In [112]:
import numpy as np
from numpy import random
n=[0,1,2]
p=[0.1, 0.4, 0.5]
cdf=[0.1, 0.5, 1]

x = np.random.uniform(0,1,1000)

M = []
def sample(M,p):
    for i in x:
        if i<=0.1:
            M.append(0)
        elif 0.1<i<=0.5:
            M.append(1)
        else:
            M.append(2)
    return M

sample(M,p)

unique_data = np.unique(M)
resdata = []
for j in unique_data:
    resdata.append(M.count(0))
    resdata.append(M.count(1))
    resdata.append(M.count(2))
    a=np.array(resdata)
    pb=a/1000
    print(pb)
    
    




[0.106 0.417 0.477]
[0.106 0.417 0.477 0.106 0.417 0.477]
[0.106 0.417 0.477 0.106 0.417 0.477 0.106 0.417 0.477]
